type: object
properties:
  id:
    type: string
    readOnly: true
    example: VmwOO9HeTEj20kxM
  name:
    type: string
    example: My Folder
  parentFolderId:
    type: string
    nullable: true
    example: 0rtUt1wbLX592XDd
    description: Unique identifier of the parent folder. Set to null to move to the root.
  projectId:
    type: string
    example: 12345
    description: Unique identifier of the project the folder belongs to.
  createdAt:
    type: string
    format: date-time
    readOnly: true
  updatedAt:
    type: string
    format: date-time
    readOnly: true
required:
  - name
